name: clisops_core
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.10,<3.15
  - cftime >=1.4.1
  - filelock >=3.15.4
  - geopandas >=1.0.0
  - jinja2 >=2.11
  - loguru >=0.5.3
  - numpy >=1.23.0,<2.1
  - packaging >=23.2
  - pandas >=1.5.0
  - roocs-grids >=0.1.2
  - xarray >=2022.6.0 # Problems can occur with regridding, see: https://github.com/pydata/xarray/issues/7794
  # Extras
  - xesmf >=0.8.2
  # IO
  - netcdf4 >=1.4
  - pooch >=1.8.0
  # Dev tools and testing
  - pip >=26.0.1
  - bump-my-version >=1.3.0
  - codespell >=2.4.2
  - coverage >=7.5.0
  - deptry >=0.25.1
  - flake8 >=7.3.0
  - flake8-rst-docstrings >=0.4.0
  - flit >=3.11.0,<4.0
  - mypy >=1.20.0
  - numpydoc >=1.10.0
  - prek >=0.3.0
  - pytest >=9.0.2
  - pytest-cov >=7.0.0
  - pytest-xdist >=3.2.0
  - ruff >=0.15.9
  - tox >=4.52.0
  - tox-gh >=1.7.1
  - vulture >=2.14
  - watchdog >=6.0.0
